export const list = [
    {
      id: 1,
      cover: "../images/list/p-1.png",
      name: "Red Carpet Real Estate",
      location: "210 Zirak Road, Canada",
      category: "For Rent",
      price: "$3,700",
      type: "Apartment",
      bedrooms:"3 Bedrooms",
      bathroom:"2 Bathrooms",
      area:"5×7 m",
      state:"Canada"
    },
    {
      id: 2,
      cover: "../images/list/p-2.png",
      name: "Fairmount Properties",
      location: "5698 Zirak Road, New York",
      category: "For Sale",
      price: "$9,750",
      type: "Condos",
      bedrooms:"2 Bedrooms",
      bathroom:"2 Bathrooms",
      area:"4×5 m",
      state:"New York"
    },
    {
      id: 3,
      cover: "../images/list/p-7.png",
      name: "The Real Estate Corner",
      location: "5624 Mooker Market, London",
      category: "For Rent",
      price: "$5,860",
      type: "Offices",
      bedrooms:"4 Bedrooms",
      bathroom:"2 Bathrooms",
      area:"6×8 m",
      state:"London"
    },
    {
      id: 4,
      cover: "../images/list/p-4.png",
      name: "Herringbone Realty",
      location: "5621 Liverpool, London",
      category: "For Sale",
      price: "$7,540",
      type: "Homes & Villas",
      bedrooms:"5 Bedrooms",
      bathroom:"3 Bathrooms",
      area:"10×8 m",
      state:"London"
    },
    {
      id: 5,
      cover: "../images/list/p-5.png",
      name: "Brick Lane Realty",
      location: "210 Montreal Road, Canada",
      category: "For Rent",
      price: "$4,850",
      type: "Commercial",
      bedrooms:"4 Bedrooms",
      bathroom:"2 Bathrooms",
      area:"6×8 m",
      state:"Canada"
    },
    {
      id: 6,
      cover: "../images/list/p-6.png",
      name: "Banyon Tree Realty",
      location: "210 Zirak Road, Canada",
      category: "For Sale",
      price: "$2,742",
      type: "Apartment",
      bedrooms:"4 Bedrooms",
      bathroom:"3 Bathrooms",
      area:"5×5 m",
      state:"Canada"
    },
    {
        id: 7,
        cover: "../images/list/id7.png",
        name: "Shamco Apartments 535 W 162nd St",
        location: "535-537 W 162nd St in Washington Heights, New York, 10032",
        price: "$5,742",
        type: "Apartment",
        bedrooms:"4 Bedrooms",
        bathroom:"1 Bathrooms",
        area:"4×2 m",
        state:"New York"
      },
      {
        id: 8,
        cover: "../images/list/id8.jpg",
        name: "Palm Harbour",
        location: "83 CRAIG ST|Brant, Ontario N3R2N5,Canada",
        price: "$1,542",
        type: "Offices",
        bedrooms:"5 rooms",
        bathroom:"3 Bathrooms",
        area:"8×8 m",
        state:"Canada"
      },
      {
        id: 9,
        cover: "../images/list/id9.jpg",
        name: "Faulkner Ave",
        location: "58 Grand Ave Unit 1,Queens,New York",
        price: "$2,675",
        type: "Condos",
        bedrooms:"3 Bedrooms",
        bathroom:"2 Bathrooms",
        area:"5×7 m",
        state:"New York"
      },
      {
        id: 10,
        cover: "../images/list/id10.jpg",
        name: "Beverly Springfield",
        location: "823 Saratoga Ave,Kings,New York",
        price: "$3,150",
        type: "Condos",
        bedrooms:"4 Bedrooms",
        bathroom:"2 Bathrooms",
        area:"6×5 m",
        state:"New York"
      },
      {
        id: 11,
        cover: "../images/list/id11.jpg",
        name: "Blossom Field",
        location: "1693 E 94th St in Canarsie, Brooklyn, 11236,New York",
        price: "$2,690",
        type: "Apartment",
        bedrooms:"5 Bedrooms",
        bathroom:"3 Bathrooms",
        area:"7×7 m",
        state:"New York"
      },
      {
        id: 12,
        cover: "../images/list/id12.jpg",
        name: "Rising Reality",
        location: "4418 Baychester Ave in Wakefield, White Plains, 10466,New York",
        price: "$2,800",
        type: "Apartment",
        bedrooms:"2 Bedrooms",
        bathroom:"2 Bathrooms",
        area:"5×7 m",
        state:"New York"
      },
      {
        id: 13,
        cover: "../images/list/id13.jpg",
        name: "Greenyard Properties",
        location: "Beach 44 St, Far Rockaway, 11691,Canada",
        price: "$3,215",
        type: "Apartment",
        bedrooms:"4 Bedrooms",
        bathroom:"2 Bathrooms",
        area:"9×8 m",
        state:"Canada"
      },
      {
        id: 14,
        cover: "../images/list/id14.jpg",
        name: "Mooker Realty",
        location: "1059 E 80th St in Canarsie, Brooklyn, 11236,Canada",
        price: "$1,820",
        type: "Apartment",
        bedrooms:"2 Bedrooms",
        bathroom:"2 Bathrooms",
        area:"5×7 m",
        state:"Canada"
      },
      {
        id: 15,
        cover: "../images/list/id15.jpg",
        name: "Heodine Properties",
        location: "5322 Avenue I Unit 1 in Flatlands, Brooklyn, 11234,Canada",
        price: "$2,600",
        type: "Apartment",
        bedrooms:"3 Bedrooms",
        bathroom:"2 Bathrooms",
        area:"5×7 m",
        state:"Canada"
      },
  ]